package personal;

import java.util.Scanner;

public class MoneyChange {
    static int calucatecoinwhile(int money){
        int numberOfCoin =0 ;
        while(money>0){
            if(money>10){
                money -= 10;
            }else if(money>5){
                money -=5;
            }else{
                money-=1;
            }
            numberOfCoin++;
        }
        return numberOfCoin;
    }
    static int calucatecoinoneLine(int money){
        return money/10 + money%10/5 + money%5;
    }


    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("THe the amount");
        int money = scanner.nextInt();
        //System.out.println(calucatecoinwhile(money));
        System.out.println(calucatecoinoneLine(money));
    }
}
/*# Generated by NetworkManager
        search iiit.in
        nameserver 172.16.1.60*/

